version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.15.0-browsers
    working_directory: ~/controlCamiones
    steps:
    #comando de circleci para pararse en la rama correspondiente
      - checkout
      - run: npm install
      #guardado de depndencias instaladas en este paso
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:12.15.0-browsers
    working_directory: ~/controlCamiones
    steps:
      - checkout
      #se recupera dependencias cacheadas o guardadas en el paso anterior
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
            #se ejecuta comando de test
      - run: npm test --no-watch
  deployment_test:
    docker:
      - image: circleci/android:api-28
      - image: circleci/node:12.15.0
    working_directory: ~/controlCamiones
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
        #se ejecuta instalacion de ionic      
      - run: sudo npm install -g @ionic/cli
        #se compila ionic 
      - run: ionic build
        #se pasa a codigo nativo android
      - run: ionic capacitor add android
        #se genera apk
      - run: 

        #se construye apk
        #subirlo a algun servidor en especial
        #generar un email con apk o un repositorio de versiones que diga rama, apk


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deployment_test:
          requires:
            - build
          #filters:
           # branches:
            #  only: master  

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

   
