version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.15.0-browsers
    #working_directory: ~/controlCamiones
    steps:
     #working_directory: ~/Test-CI
      - checkout
      - run: pwd
      - run: sudo npm install -g @ionic/cli
      - run: npm install
      - run: ls node_modules
      #- run: npm test --no-watch

  test:
    docker:
      - image: circleci/node:12.15.0-browsers
    working_directory: ~/controlCamiones
    steps:
        #working_directory: ~/Test-CI
      - checkout  
      - run: pwd
      - run: ls
      - run: npm test --no-watch
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          #filters:
           # branches:
            #  only: master  

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

   
