version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.15.0
    working_directory: ~/Test-CI
    steps:
     #working_directory: ~/Test-CI
      - checkout
      - run: sudo npm install -g @ionic/cli
      - run: npm install
  test:
    docker:
      - image: circleci/node:12.15.0
    working_directory: ~/Test-CI
    steps:
        #working_directory: ~/Test-CI
      - run: ls  
      - run: sudo npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          #filters:
           # branches:
            #  only: master  

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

   
